//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitsCs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyComments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyComments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitsCs.KeyComments", typeof(KeyComments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type and size in bits.
        /// </summary>
        internal static string Bitpix {
            get {
                return ResourceManager.GetString("Bitpix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of groups.
        /// </summary>
        internal static string Gcount {
            get {
                return ResourceManager.GetString("Gcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of dimensions.
        /// </summary>
        internal static string Naxis {
            get {
                return ResourceManager.GetString("Naxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parameters.
        /// </summary>
        internal static string Pcount {
            get {
                return ResourceManager.GetString("Pcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fits-compliant file.
        /// </summary>
        internal static string Simple_True {
            get {
                return ResourceManager.GetString("Simple_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary table extension.
        /// </summary>
        internal static string Xtension_Bintable {
            get {
                return ResourceManager.GetString("Xtension_Bintable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image extension.
        /// </summary>
        internal static string Xtension_Image {
            get {
                return ResourceManager.GetString("Xtension_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table extension.
        /// </summary>
        internal static string Xtension_Table {
            get {
                return ResourceManager.GetString("Xtension_Table", resourceCulture);
            }
        }
    }
}
